# Building NNs using PyTorch
---
## 목차
1. [torch.Tensor](#torch.Tensor)
2. [Tensor operations](#Tensor-operations)
3. [Autograd](#Autograd)
---

## torch.Tensor

* Like tensors in linear algebra, PyTorch tensors are arrays which can be multi-dimensional
* PyTorch tensors are similarto NumPy ndarrays except for GPU acceleration

In [1]:
import torch
import numpy as np

In [2]:
# Initialize with Python lists
arr = [[1,2],[2,3]]

arr_n = np.array(arr)
print(type(arr_n))
print(arr_n)

arr_t = torch.Tensor(arr)
print(type(arr_t))
print(arr_t)

<class 'numpy.ndarray'>
[[1 2]
 [2 3]]
<class 'torch.Tensor'>
tensor([[1., 2.],
        [2., 3.]])


In [3]:
# Initialization : ones& zeros
print(np.ones((2,3)))
print(np.zeros((2,3)))
print(torch.ones((2,3)))
print(torch.zeros((2,3)))

# Initialization : ones_like & zeros_like
print(np.ones_like(arr_n))
print(np.zeros_like(arr_n))
print(torch.ones_like(arr_t))
print(torch.zeros_like(arr_t))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [ ]:
# Two ways of specifying data type

## 1. Use keyword argument dtype
print(torch.ones((2,3),dtype = torch.int))
print(torch.ones((2,3),dtype = torch.float))

## 2. Use typed tensors
ft = torch.FloatTensor([1,2])
print(ft)
print(ft.dtype)

## Tensor operations


### Accessing elements

In [7]:
# Accessing elements

## Access is similar to NumPy but it always returns Tensor
arr_t = torch.Tensor([[1,2],[2,3]])
print(arr_t[0,1])

## Get a Python Number
print(arr_t[0,1].item())

## Update is same with NumPy
arr_t[0,1] = 0
print(arr_t)

tensor(2.)
2.0
tensor([[1., 0.],
        [2., 3.]])


### Slicing

In [9]:
# Slicing

t = torch.Tensor([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
print(t)

print(f"t[:2] = {t[:2]}")
print(f"t[:,1:] = {t[:,1:]}")
print(f"t[1:,1:3] = {t[1:,1:3]}")
print(f"t[:,:-1] = {t[:,:-1]}")
print(f"t[:,-3:-1] = {t[:,-3:-1]}")
print("---------------------------------")
t[1:,1:3] = 0
print(t)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])
t[:2] = tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.]])
t[:,1:] = tensor([[2., 3., 4.],
        [3., 4., 5.],
        [6., 7., 8.]])
t[1:,1:3] = tensor([[3., 4.],
        [6., 7.]])
t[:,:-1] = tensor([[1., 2., 3.],
        [2., 3., 4.],
        [5., 6., 7.]])
t[:,-3:-1] = tensor([[2., 3.],
        [3., 4.],
        [6., 7.]])
---------------------------------
tensor([[1., 2., 3., 4.],
        [2., 0., 0., 5.],
        [5., 0., 0., 8.]])


### Shape & Transpose

In [10]:
# Shape & Transpose

## Transpose of 2-D tensor(matrix)
X = torch.Tensor([[1,2,3],[4,5,6]])
print(X.shape)
print(X.T.shape)

torch.Size([2, 3])
torch.Size([3, 2])


### Sum

In [11]:
# torch.sum(input, dim, keepdim = False, *,dtype = None)
## dim : 0 -> col, 1 -> row
## keepdim : True / False 
print(X)
print(X.sum(0))
print(X.sum(1))
print(X.sum(0,keepdim=True))
print(X.sum(1,keepdim=True))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([[5., 7., 9.]])
tensor([[ 6.],
        [15.]])


### Mean

In [12]:
#torch.mean(input,dim,keepdim=False,*)
print(X)
print(X.mean())
print(X.mean(0))
print(X.mean(1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


### Max

In [13]:
# torch.max(input, dim, keepdim=False)
print(X)
print(X.max())
print(X.max(0))
print(X.max(1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(6.)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))


### Binary Operators

In [15]:
X = torch.Tensor([[1,2,3],[4,5,6]])
Y = torch.Tensor([[1,0,2],[1,0,1]])
x = torch.FloatTensor([1,2])
y = torch.FloatTensor([1,1])

# Addition
print(X+Y)

# Element-wise multiplication
print(X*Y)

# Matrix Multiplication
print(torch.matmul(X.T,Y))
print(torch.matmul(X,Y.T))

# inner product (내적)
print(torch.inner(x,y))

tensor([[2., 2., 5.],
        [5., 5., 7.]])
tensor([[1., 0., 6.],
        [4., 0., 6.]])
tensor([[ 5.,  0.,  6.],
        [ 7.,  0.,  9.],
        [ 9.,  0., 12.]])
tensor([[ 7.,  4.],
        [16., 10.]])
tensor(3.)


### View

In [17]:
X = torch.Tensor([[[1,3,1],[0,2,1],[1,2,5]],[[0,4,2],[1,1,2],[3,2,1]]])

print(f"X.shape : {X.shape}")
print(X)
print("-------------")

Y = X.view(3,2,3)
print(f"Y.shape : {Y.shape}")
print(Y)
print("-------------")

Z = X.view(6,3)
print(f"Z.shape : {Z.shape}")
print(Z)


X.shape : torch.Size([2, 3, 3])
tensor([[[1., 3., 1.],
         [0., 2., 1.],
         [1., 2., 5.]],

        [[0., 4., 2.],
         [1., 1., 2.],
         [3., 2., 1.]]])
-------------
Y.shape : torch.Size([3, 2, 3])
tensor([[[1., 3., 1.],
         [0., 2., 1.]],

        [[1., 2., 5.],
         [0., 4., 2.]],

        [[1., 1., 2.],
         [3., 2., 1.]]])
-------------
Z.shape : torch.Size([6, 3])
tensor([[1., 3., 1.],
        [0., 2., 1.],
        [1., 2., 5.],
        [0., 4., 2.],
        [1., 1., 2.],
        [3., 2., 1.]])


### Squeeze & Unsqueeze

In [30]:
X = torch.Tensor([[[1,2,3]],[[4,5,6]],[[7,8,9]],[[10,11,12]]])
print(X.shape)
Y = X.squeeze(dim=1)
print(Y.shape)
Z = Y.unsqueeze(dim=1)
print(Z.shape)

torch.Size([4, 1, 3])
torch.Size([4, 3])
torch.Size([4, 1, 3])


### Broadcasting

In [31]:
X = torch.Tensor([[[1,3,1],[0,2,1],[1,2,5]],[[0,4,2],[1,1,2],[3,2,1]]])

print(f"X.shape : {X.shape}")
print(X)

Y1 = torch.ones((1,1,3))
Y2 = torch.ones((1,3))
Y3 = torch.ones(3)

print(X+Y1)
print(X+Y2)
print(X+Y3)

X.shape : torch.Size([2, 3, 3])
tensor([[[1., 3., 1.],
         [0., 2., 1.],
         [1., 2., 5.]],

        [[0., 4., 2.],
         [1., 1., 2.],
         [3., 2., 1.]]])
tensor([[[2., 4., 2.],
         [1., 3., 2.],
         [2., 3., 6.]],

        [[1., 5., 3.],
         [2., 2., 3.],
         [4., 3., 2.]]])
tensor([[[2., 4., 2.],
         [1., 3., 2.],
         [2., 3., 6.]],

        [[1., 5., 3.],
         [2., 2., 3.],
         [4., 3., 2.]]])
tensor([[[2., 4., 2.],
         [1., 3., 2.],
         [2., 3., 6.]],

        [[1., 5., 3.],
         [2., 2., 3.],
         [4., 3., 2.]]])


### ndarray <-> tensor

In [34]:
a = np.array([1,2,3])
print(a)
t = torch.from_numpy(a)
t1 = torch.from_numpy(a)
print(t)
c = t.numpy()
print(c)

[1 2 3]
tensor([1, 2, 3])
[1 2 3]


## Autograd

* torch.autograd is PyTorch's <b>automatic differentiation engine</b> that powers neural network training


1. initialization
> set requires_grad to True if you want to track the gradient

In [36]:
w = torch.randn(2,requires_grad = True)
x = torch.ones(2)
print("w",w.requires_grad)
print("x",x.requires_grad)


w True
x False


2. backward()
> Computes the sum of gradients of given tensors w.r.t. the leaves of computation graphs
* Accessing the gradient
> w.grad : w is a tensor whose requires_grad is True

* Torch.no_grad
```python
with torch.no_grad():
    w = w - lr * w.grad
```
> Torch.no_grad disables gradient calculation

3. in-place operations and Autograd
> An in-place operation is an operation that changes <b>directly the content of a given Tensor</b> without making a copy
> > <b> Anyway, never use in-place operation to the tensors on the path from the parameters to the loss</b>

- in-place operations
```python
A += X
a[i:] = 0
```
- Without in-place operations
```python
A = A + X
mask = torch.ones_like(a)
mask[i:] = 0
a = a*mask
```