In [2]:
import torch
import numpy as np
print(torch.__version__)

1.7.1


# Initialize with Python lists

In [3]:
arr = [[1,2],[3,4]]

In [4]:
# numpy 
arr_n = np.array(arr)
print("numpy array type : {}".format(type(arr_n)))
print("numpy array : \n {}".format(arr_n))

# torch
arr_t = torch.Tensor(arr)
print("numpy array type : {}".format(type(arr_t)))
print("numpy array : \n {}".format(arr_t))

numpy array type : <class 'numpy.ndarray'>
numpy array : 
 [[1 2]
 [3 4]]
numpy array type : <class 'torch.Tensor'>
numpy array : 
 tensor([[1., 2.],
        [3., 4.]])


In [5]:
# Initialization

# np.array
print(np.ones((2,3)))
print(np.zeros((2,3)))

# torch.Tensor
print(torch.ones(2,3))
print(torch.zeros(2,3))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# ones_like : 기존 matrix과 동일한 shape의 matrix를 생성하기 위한 용도
print(np.ones_like(arr_n))
print(np.zeros_like(arr_n))

print(torch.ones_like(arr_t))
print(torch.zeros_like(arr_t))

[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


# Specifying data type

In [7]:
# Use keyword argument dtype
print(torch.ones((2,3), dtype = torch.int))
print(torch.zeros((2,3,), dtype = torch.float))

# Use typed tensors
ft = torch.FloatTensor([1,2])
print(ft)
print(ft.dtype)
print(type(ft))

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1., 2.])
torch.float32
<class 'torch.Tensor'>


# Accessing elements

In [8]:
arr_t = torch.Tensor([[1,2],[3,4]])

# Access
arr_t[0,1]

# Get python number
print(arr_t[0,1].item())
print(arr_t[0,:])

# Update
arr_t[0,1] = 0
print(arr_t)

2.0
tensor([1., 2.])
tensor([[1., 0.],
        [3., 4.]])


In [9]:
# Slicing
t = torch.Tensor([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
print(t)

print(t[:2])
print(t[:2,1:])

# Negative Slicing
print(t[:,:-1])
print(t[:,-3:-1])

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.]])
tensor([[2., 3., 4.],
        [3., 4., 5.]])
tensor([[1., 2., 3.],
        [2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3.],
        [3., 4.],
        [6., 7.]])


# Shape &Transpose (matrix)

In [10]:
# Transpose
print("Original Tensor : \n{}".format(t))
print("Transpose : \n{}".format(t.T))

# Shape
print("t shape : {}".format(t.shape))
print("t.T shape : {}".format(t.T.shape))

Original Tensor : 
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])
Transpose : 
tensor([[1., 2., 5.],
        [2., 3., 6.],
        [3., 4., 7.],
        [4., 5., 8.]])
t shape : torch.Size([3, 4])
t.T shape : torch.Size([4, 3])


# Sum

In [11]:
X = torch.Tensor([[1,2,3],[4,5,6]])
print(X.sum())
print(torch.sum(X))

tensor(21.)
tensor(21.)


In [12]:
print(X.sum(dim=(0,1),keepdim= True))

tensor([[21.]])


In [13]:
# Keepdim = False
X0 = X.sum(0)
X1 = X.sum(1)
print("X dim = 0 is \n{}\nand shape : {}".format(X0,X0.shape))
print("X dim = 1 is \n{}\nand shape : {}".format(X1,X1.shape))

print("------keepdim = True-------")
# Keepdim = True
X_dim0 = X.sum(dim = 0, keepdim=True)
X_dim1 = X.sum(dim = 1 , keepdim=True)
print("X dim = 0 is \n{}\nand shape : {}".format(X_dim0,X_dim0.shape))
print("X dim = 1 is \n{}\nand shape : {}".format(X_dim1,X_dim1.shape))

X dim = 0 is 
tensor([5., 7., 9.])
and shape : torch.Size([3])
X dim = 1 is 
tensor([ 6., 15.])
and shape : torch.Size([2])
------keepdim = True-------
X dim = 0 is 
tensor([[5., 7., 9.]])
and shape : torch.Size([1, 3])
X dim = 1 is 
tensor([[ 6.],
        [15.]])
and shape : torch.Size([2, 1])


# Mean

In [14]:
print(f'''
Normal X 
{X}
X mean : {X.mean()}
X mean shape : {X.mean().shape}

--------------------------------

X.mean(0) : {X.mean(0)}
X.mean(0).shape : {X.mean(0).shape}
X.mean(0,keepdim=True).shape : {X.mean(0,keepdim=True).shape}
''')


Normal X 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
X mean : 3.5
X mean shape : torch.Size([])

--------------------------------

X.mean(0) : tensor([2.5000, 3.5000, 4.5000])
X.mean(0).shape : torch.Size([3])
X.mean(0,keepdim=True).shape : torch.Size([1, 3])



# Max

In [17]:
print(f'''
{X}
------------------------
X max : {X.max()}
arg X max : {X.argmax()}
-------dim = 1----------
X max : {X.max(1)}
arg X max : {X.argmax(1)}
X max values shape : {X.max(1).values.shape}
--------keepdim = True---------
X max : {X.max(0,keepdim=True)}
X max values shape : {X.max(0,keepdim=True).values.shape}
''')


tensor([[1., 2., 3.],
        [4., 5., 6.]])
------------------------
X max : 6.0
arg X max : 5
-------dim = 1----------
X max : torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))
arg X max : tensor([2, 2])
X max values shape : torch.Size([2])
--------keepdim = True---------
X max : torch.return_types.max(
values=tensor([[4., 5., 6.]]),
indices=tensor([[1, 1, 1]]))
X max values shape : torch.Size([1, 3])



# Binary Operators

In [19]:
X = torch.Tensor([[1,2,3],[4,5,6]])
Y = torch.Tensor([[1,0,2],[1,0,1]])

# Addition
print(f"X + Y : \n{X+Y}")

# Element-wise multiplication
print(f"Element wise mult : \n{X*Y}")

# Matrix multiplication
print(f"Matrix multiplication : \n{torch.matmul(X.T,Y)}")
print(f"Matrix multiplication : \n{torch.matmul(X,Y.T)}")

# Inner product
print(f"Inner product : {torch.dot(X[0],Y[0])}\nX[0] shape : {X[0].shape}, X[0] : {X[0]}")

X + Y : 
tensor([[2., 2., 5.],
        [5., 5., 7.]])
Element wise mult : 
tensor([[1., 0., 6.],
        [4., 0., 6.]])
Matrix multiplication : 
tensor([[ 5.,  0.,  6.],
        [ 7.,  0.,  9.],
        [ 9.,  0., 12.]])
Matrix multiplication : 
tensor([[ 7.,  4.],
        [16., 10.]])
Inner product : 7.0
X[0] shape : torch.Size([3]), X[0] : tensor([1., 2., 3.])


# Tensor manipulation

In [68]:
m = torch.rand((2,3,3))
print(m)
print(m.shape)

tensor([[[0.3564, 0.8051, 0.7059],
         [0.8325, 0.7229, 0.3858],
         [0.3478, 0.2356, 0.5386]],

        [[0.0176, 0.1548, 0.1779],
         [0.3097, 0.9111, 0.0365],
         [0.4334, 0.1034, 0.5609]]])
torch.Size([2, 3, 3])


In [69]:
# View
mv = m.view(3,2,3)
print(f"mv : \n{mv}\nshape : {mv.shape}")

mv : 
tensor([[[0.3564, 0.8051, 0.7059],
         [0.8325, 0.7229, 0.3858]],

        [[0.3478, 0.2356, 0.5386],
         [0.0176, 0.1548, 0.1779]],

        [[0.3097, 0.9111, 0.0365],
         [0.4334, 0.1034, 0.5609]]])
shape : torch.Size([3, 2, 3])


In [79]:
# Squeeze 
V = torch.rand((2,1,3))
VS = V.squeeze(dim=1)
VU = VS.unsqueeze(dim=0)
VU1 = VS.unsqueeze(dim=1)
VU2 = VS.unsqueeze(dim=2)
# VU3 = VS.unsqueeze(dim=3) -> index error 발생
print(f'''
original :
{V}
shape : {V.shape}
-------------------squeeze dim = 1-----------------
matrix :
{V.squeeze(dim=1)}
shape : {V.squeeze(dim=1).shape}
---------------unsqueeze-----------------
dim = 0
{VU}
shape : {VU.shape}

dim = 1
{VU1}
shape : {VU1.shape}

dim = 2
{VU2}
shape : {VU2.shape}

''')


original :
tensor([[[0.2920, 0.5185, 0.9047]],

        [[0.9240, 0.9311, 0.6742]]])
shape : torch.Size([2, 1, 3])
-------------------squeeze dim = 1-----------------
matrix :
tensor([[0.2920, 0.5185, 0.9047],
        [0.9240, 0.9311, 0.6742]])
shape : torch.Size([2, 3])
---------------unsqueeze-----------------
dim = 0
tensor([[[0.2920, 0.5185, 0.9047],
         [0.9240, 0.9311, 0.6742]]])
shape : torch.Size([1, 2, 3])

dim = 1
tensor([[[0.2920, 0.5185, 0.9047]],

        [[0.9240, 0.9311, 0.6742]]])
shape : torch.Size([2, 1, 3])

dim = 2
tensor([[[0.2920],
         [0.5185],
         [0.9047]],

        [[0.9240],
         [0.9311],
         [0.6742]]])
shape : torch.Size([2, 3, 1])




# Broadcasting

In [80]:
a = torch.Tensor([[1,2,3],[4,5,6]])
print(a.shape)
b = torch.Tensor([1,2])
print(b.shape)

torch.Size([2, 3])
torch.Size([2])


In [83]:
# print(a+b) -> error
print(a.T + b)
# 마지막이 같아야 한다 이 말이지~

tensor([[2., 6.],
        [3., 7.],
        [4., 8.]])


In [86]:
# ndarray <-> tensor
arr = [[1,2,3],[4,5,6]]
arr_n = np.array(arr)
arr_t = torch.from_numpy(arr_n)
print(f"arr_n type : {type(arr_n)}")
print(f"tensor type : {type(arr_t)}")
print(f"numpy type : {type(arr_t.numpy())}")

arr_n type : <class 'numpy.ndarray'>
tensor type : <class 'torch.Tensor'>
numpy type : <class 'numpy.ndarray'>
